### ISSUE TITLE
Get multiple properties inside the device information, which raises an exception

### ISSUE THREAD

**Issue by BianYuan1995** [mveril/MobileDeviceSharp#1]
Only limited device information is available

**Comment by BianYuan1995** [comment]
[MobileDeviceSharp.IDevice,"","","","",False,"",iPhone,xxxxxxxxxxxxxxxxxxxxxxxxxxxx,"iOS]([url]([url](url))) 15.1",MobileDeviceSharp.Battery,iPhone,iPhone,"iPhone10,6","iPhone X","Exception has been thrown by the target of an invocation.","Exception has been thrown by the target of an invocation.","Exception has been thrown by the target of an invocation.","Exception has been thrown by the target of an invocation.","Exception has been thrown by the target of an invocation.","Exception has been thrown by the target of an invocation.","Exception has been thrown by the target of an invocation.",3C2EFF92513E,"Exception has been thrown by the target of an invocation.","Exception has been thrown by the target of an invocation.","Exception has been thrown by the target of an invocation.","Exception has been thrown by the target of an invocation.",arm64,False,"1377717869504 (IDeviceHandle)",False

**Comment by mveril** [comment]
Thank you for your interest in my project. For some protected informations such as language or locale, the device must be paired with the computer. To do this, you must pair the device and do what libimobiledevice calls a handshake using a `LockdownSession` before using these properties. For that you need to use this method https://github.com/mveril/MobileDeviceSharp/blob/35a198bae2cf964b40d2d6dc99c1532a7b5c83e2/src/MobileDeviceSharp/LockdownSession.cs#L346 or one of these overloads and accept pairing on the iPhone if this is necessary.
This method returns a `Task<bool>` that runs until you accept the pairing.
Can you explain in more detail which properties you are interested in?
Sory for the delay of my response I didn't see the notification.

**Comment by BianYuan1995** [comment]
Thanks for your reply, I succeeded. it is a great project.
